### Task-1
#### Write a NumPy program to perform efficient array operations as below

In [3]:
import numpy as np

##### Create a NumPy array using the 'np.array' function 

In [5]:
a = np.array([[3, 4, 5, 6, 7], [13, 14, 15, 16, 17], [23, 24, 25, 26, 27]])
print("Array a :\n", a)

Array a :
 [[ 3  4  5  6  7]
 [13 14 15 16 17]
 [23 24 25 26 27]]


##### Perform array operations such as squaring each element and calculating the sum using NumPy functions

In [6]:
b = np.square(a)
print(b)

[[  9  16  25  36  49]
 [169 196 225 256 289]
 [529 576 625 676 729]]


In [7]:
sum = np.add(a,b)
print(sum)

[[ 12  20  30  42  56]
 [182 210 240 272 306]
 [552 600 650 702 756]]


##### Reshaped the array into a 2D array using the 'reshape' method

In [10]:
b = np.arange(2, 8)
print("1D Array b :", b)

1D Array b : [2 3 4 5 6 7]


In [16]:
print("2D Array b :\n", b.reshape(2,3))

2D Array b :
 [[2 3 4]
 [5 6 7]]
