### Task-5
#### Write a Python program in NumPy to perform a vectorization operation on the entire array with the following steps

In [2]:
import numpy as np

##### Create two arrays ('array1' and 'array2')

In [32]:
array1 = np.array([[3, 7, 8, 5, 6], [3, 2, 6, 7, 5]])
print("Array 1 :\n", array1)

Array 1 :
 [[3 7 8 5 6]
 [3 2 6 7 5]]


In [33]:
array2 = np.array([[4, 6, 3, 2, 1], [8, 2, 3, 8, 2]])
print("Array 2 :\n", array2)

Array 2 :
 [[4 6 3 2 1]
 [8 2 3 8 2]]


##### Perform vectorized addition ('array1 + array2'), multiplication ('array1 * array2'), and square root ('np.sqrt(array1)').

###### addition ('array1 + array2')

In [34]:
addition = array1 + array2
print("Vectorized Addition Result :\n", addition)

Vectorized Addition Result :
 [[ 7 13 11  7  7]
 [11  4  9 15  7]]


###### multiplication ('array1 * array2')

In [35]:
multiplication = array1 * array2
print("Vectorized Multiplication Result :\n", multiplication)

Vectorized Multiplication Result :
 [[12 42 24 10  6]
 [24  4 18 56 10]]


###### square root ('np.sqrt(array1))

In [36]:
square_root = np.sqrt(array1)
print("Vectorized Square Root Result :\n", square_root)

Vectorized Square Root Result :
 [[1.73205081 2.64575131 2.82842712 2.23606798 2.44948974]
 [1.73205081 1.41421356 2.44948974 2.64575131 2.23606798]]
