## NumPy

- Numpy library is special and very useful for data science
- It is most fundamentale and core scientific library
- It is supported numarical operations and large multidimentional array of object
- Numpy array are called ndarray and n dimentional array
- A array one dimentional is called a vector while having two dimentional is called matrix
- __pip install numpy__

### What is NumPy?
- Numpy is very useful for performing logical and mathematical calculations on arrays and matrices
- This tool performs these operations much faster and more efficiently than lists
- Numpy uses less memory and storage space, which is the main advantage

### Why NumPy?
- Numpy arrays are faster and more compact than lists
- An array consumes less memory and is convenient to use
- Numpy uses much less memory to store data and it provides a mechanism of specifying the data types

### Difference between python list and numpy array
- Numpy can contain similar datatypes while List contains different types of datatypes
- Numpy is homogeneous while List is both homogeneous and heterogeneous
- Numpy requires smaller memory consumption as compared to list while List requires more memory as compared to numpy array
- In Numpy, each item is stored in a sequential manner while List stores item in random location of  the memory
- Numpy is faster as compared to list while List is slow as compared to numpy array

In [11]:
import numpy as np

#### one dimentional array

In [3]:
n1 = np.array([3, 4, 5, 6, 7])
print(n1)
print("Type of n1 :", type(n1))

[3 4 5 6 7]
Type of n1 : <class 'numpy.ndarray'>


In [4]:
print("Shape of numpy array n1 :", n1.shape)
print("Size of numpy array n1 :", n1.size)
print("No of dimentional of numpy array n1 :", n1.ndim)

Shape of numpy array n1 : (5,)
Size of numpy array n1 : 5
No of dimentional of numpy array n1 : 1


#### two dimentional array

In [49]:
n2 = np.array([[3, 4, 5, 6, 7], [13, 14, 15, 16, 17], [23, 24, 25, 26, 27]])        
print(n2)

[[ 3  4  5  6  7]
 [13 14 15 16 17]
 [23 24 25 26 27]]


In [50]:
print("Shape of numpy array n2 :", n2.shape)
print("Size of numpy array n2 :", n2.size)
print("No of dimentional of numpy array n2 :", n2.ndim)

Shape of numpy array n2 : (3, 5)
Size of numpy array n2 : 15
No of dimentional of numpy array n2 : 2


In [60]:
print("Access 3 element :", n2[0,0])
print("Access 17 element :", n2[1,4])
print("Access 24 element :", n2[2,1])

Access 3 element : 3
Access 17 element : 17
Access 24 element : 24


##### convert row vector to column vector using numpy

In [7]:
n3 = np.array([[3, 4, 5, 6, 7], [13, 14, 15, 16, 17], [23, 24, 25, 26, 27]])
print(n3.reshape(5,3))

[[ 3  4  5]
 [ 6  7 13]
 [14 15 16]
 [17 23 24]
 [25 26 27]]


##### create an array column wise

In [35]:
n4 = np.array([[3, 4, 5, 6, 7], [13, 14, 15, 16, 17], [23, 24, 25, 26, 27]])
print(np.column_stack(n4))

[[ 3 13 23]
 [ 4 14 24]
 [ 5 15 25]
 [ 6 16 26]
 [ 7 17 27]]


#### three dimentional array

In [56]:
n6 = np.array([[[3, 4, 5, 6, 7],[13, 14, 15, 16, 17],[31, 41, 51, 61, 71]],
       [[23, 24, 25, 26, 27],[32, 42, 52, 62, 72],[33, 34, 35, 36, 37]],
       [[43, 44, 45, 46, 47],[53, 54, 55, 56, 57],[36, 46, 56, 66, 76]]])
print(n6)

[[[ 3  4  5  6  7]
  [13 14 15 16 17]
  [31 41 51 61 71]]

 [[23 24 25 26 27]
  [32 42 52 62 72]
  [33 34 35 36 37]]

 [[43 44 45 46 47]
  [53 54 55 56 57]
  [36 46 56 66 76]]]


In [57]:
print("Shape of numpy array n6 :", n6.shape)
print("Size of numpy array n6 :", n6.size)
print("No of dimentional of numpy array n6 :", n6.ndim)

Shape of numpy array n6 : (3, 3, 5)
Size of numpy array n6 : 45
No of dimentional of numpy array n6 : 3


In [65]:
print("Access 24 element :", n6[1][0][1])
print("Access 45 element :", n6[2][0][2])
print("Access 36 element :", n6[1][2][3])
print("Access first array of second matrix array :", n6[1,0])

Access 24 element : 24
Access 45 element : 45
Access 36 element : 36
Access first array of second matrix array : [23 24 25 26 27]


#### four dimentional array

In [62]:
n7 = np.array([[[[2, 3, 4, 5],[3, 4, 5, 3],[5, 6, 7, 2]],
               [[1, 2, 3, 2],[5, 6, 7, 1],[8, 9, 0, 4]],
               [[0, 2, 6, 1],[4, 6, 8, 3],[5, 4, 6, 1]]],
               
               [[[2, 7, 2, 7],[5, 1, 6, 2],[7, 6, 2, 4]],
               [[5, 6, 2, 1],[0, 2, 7, 5],[4, 1, 5, 0]],
               [[0, 2, 6, 4],[5, 4, 1, 1],[1, 0, 4, 5]]]])
print(n7)

[[[[2 3 4 5]
   [3 4 5 3]
   [5 6 7 2]]

  [[1 2 3 2]
   [5 6 7 1]
   [8 9 0 4]]

  [[0 2 6 1]
   [4 6 8 3]
   [5 4 6 1]]]


 [[[2 7 2 7]
   [5 1 6 2]
   [7 6 2 4]]

  [[5 6 2 1]
   [0 2 7 5]
   [4 1 5 0]]

  [[0 2 6 4]
   [5 4 1 1]
   [1 0 4 5]]]]


In [63]:
print("Shape of numpy array n7 :", n7.shape)
print("Size of numpy array n7 :", n7.size)
print("No of dimentional of numpy array n7 :", n7.ndim)

Shape of numpy array n7 : (2, 3, 3, 4)
Size of numpy array n7 : 72
No of dimentional of numpy array n7 : 4


In [69]:
print("Access first set :\n", n7[0])
print("\nAccess fisrt matrix of second set :\n", n7[1][0])
print("\nAccess third array of first set of second set array :", n7[1][0][2])
print("Access 4 element :", n7[1,0,2,3])

Access first set :
 [[[2 3 4 5]
  [3 4 5 3]
  [5 6 7 2]]

 [[1 2 3 2]
  [5 6 7 1]
  [8 9 0 4]]

 [[0 2 6 1]
  [4 6 8 3]
  [5 4 6 1]]]

Access fisrt matrix of second set :
 [[2 7 2 7]
 [5 1 6 2]
 [7 6 2 4]]

Access third array of first set of second set array : [7 6 2 4]
Access 4 element : 4


#### covert list into array

In [16]:
a = [3, 4, 5, 2, 1]
b = [5, 1, 2, 4, 9]
c = np.array((a,b))
print(c)

[[3 4 5 2 1]
 [5 1 2 4 9]]


In [18]:
a = ['a', 'b', 'c', 'd']
b = ['e', 'f', 'g', 'h']
d = np.array((a,b))
print(d)

[['a' 'b' 'c' 'd']
 ['e' 'f' 'g' 'h']]


#### zero() funtion
It is used for create zero matrix <br>
If all the elements are zero in a matrix, then it is called a zero matrix and generally denoted by 0.

In [9]:
a = np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


#### full() function
It is used to return a new array of a given shape and data type filled with fill_value

In [66]:
a = np.full((2,2),0)
print(a)

[[0 0]
 [0 0]]


#### eye() function
It is used for create identity matrix <br>
A square matrix in which all elements of the principal diagonal are 1 and all the other elements are 0 is called a identity matrix

In [30]:
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Parameter k determines whether the diagonal is main, upper, or lower <br>
the main diagonal is assigned by 0 k (default) <br>
the upper diagonal by a positive k <br>
the lower diagonal by a negative k <br>

In [29]:
a = np.eye(3, k=1)
print(a)

[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


In [28]:
a = np.eye(3, k=-2)
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [1. 0. 0.]]


#### transpose of matrix
The transpose of a matrix is obtained by moving the rows data to the column and columns data to the rows

In [16]:
m = np.array([[3, 2, 4],[5, 2, 3]])
print(m)

[[3 2 4]
 [5 2 3]]


In [17]:
k = m.T               
print(k)

[[3 5]
 [2 2]
 [4 3]]


#### arange() function
It is used for create an array <br> __np.arange(start, stop, step)__ <br> This function generates a sequence of numbers within the specified range

In [74]:
a = np.arange(2, 8)
print(a)

[2 3 4 5 6 7]


In [19]:
b = np.arange(10, 100, 5)
print(b)

[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


##### print even number using arange() function

In [12]:
a1 = np.arange(0, 20, 2)
print(a1)         

[ 0  2  4  6  8 10 12 14 16 18]


##### print odd number using arange() function

In [13]:
a1 = np.arange(1, 20, 2)
print(a1)         

[ 1  3  5  7  9 11 13 15 17 19]


#### reshape() function
It is used to create a new array of the same size but of different dimensions <br> That means changing the shape of an array.

In [76]:
print(a.reshape(2,3))    

[[2 3 4]
 [5 6 7]]


In [22]:
print(b.reshape(2, 3, 3))

[[[10 15 20]
  [25 30 35]
  [40 45 50]]

 [[55 60 65]
  [70 75 80]
  [85 90 95]]]


##### create one array using arange funtion and reshape into two & three dimentional array (minimum 30 elements)

In [17]:
a1 = np.arange(6, 36)
print(a1)

[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29
 30 31 32 33 34 35]


In [18]:
a2 = a1.reshape(6,5)
print(a2)
a2.ndim

[[ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]]


2

In [81]:
a3 = a1.reshape(2, 3, 5)
print(a3)
a3.ndim

[[[ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]]

 [[21 22 23 24 25]
  [26 27 28 29 30]
  [31 32 33 34 35]]]


3

#### transpose() function
The transpose of a matrix is obtained by moving the rows data to the column and columns data to the rows

In [82]:
m = np.array([[3, 4, 2],[8, 5, 7],[1, 2, 5],[2, 7, 6]])
print(np.transpose(m))

[[3 8 1 2]
 [4 5 2 7]
 [2 7 5 6]]


In [26]:
m = np.array([[12],[14],[11],[13]])
print(np.transpose(m))

[[12 14 11 13]]


#### dot() function
It used to compute dot products of two given matrix <br> It is multiplies each value from one row with the values from another column and adds them together

In [84]:
a = np.array([[3, 4],[1, 2],[7, 5]])
b = np.array([[4, 3],[3, 5]])
print(np.dot(a,b))

[[24 29]
 [10 13]
 [43 46]]


In [88]:
a = np.array([[10],[20]])
b = np.array([[4,7],[8,2],[1,6]])
print(np.dot(b,a))

[[180]
 [120]
 [130]]


#### linalg.inv() function
It is used to calculate the inverse of a matrix <br> inv() belongs to linalg() that stand for linear algebra

In [92]:
A = np.array([[1, 2],[4, 1]])
A_inv = np.linalg.inv(A)
print(A_inv)

[[-0.14285714  0.28571429]
 [ 0.57142857 -0.14285714]]


In [91]:
B = np.array([[0, 1, 2],[1, 2, 3],[3, 1, 1]])
B_inv = np.linalg.inv(B)
print(B_inv)

[[ 0.5 -0.5  0.5]
 [-4.   3.  -1. ]
 [ 2.5 -1.5  0.5]]


#### sort() function
##### What is the sort() function in numpy? 
- It is used to sort an array in ascending order or descending order
- It returns a sorted copy of an array <br><br>
__numpy.sort(a, axis=-1, kind=None, order=None)__
##### Parameters of sort() function
- __a -__ array-like object <br>
&emsp; The input array to be sorted
- __axis -__ 0, -1 or none <br>
&emsp;&emsp;&emsp; The axis along which the array has to be sort <br>
&emsp;&emsp;&emsp; If nothing is mentioned, then the array is flattened before sorting <br>
&emsp;&emsp;&emsp; By default, the array is sorted along the last axis that denoted by axis = -1
- __kind -__ {‘quicksort’, ‘mergesort’, ‘heapsort’, ‘stable’} <br>
&emsp;&emsp;&emsp;&nbsp; In numpy, choose any sorting algorithms {‘quicksort’, ‘mergesort’, ‘heapsort’, ‘stable’} <br>
&emsp;&emsp;&emsp;&nbsp; By default, the input array will be sorted by using quicksort
- __order -__ order of sorting {string or list} <br>
&emsp;&emsp;&emsp;&nbsp; This parameter specifies the field along which the sorting has to be done <br>
&emsp;&emsp;&emsp;&nbsp; It usually used when we have a field defined array.

In [11]:
A = np.array([[25, 20, 22],[21, 24, 20],[26, 27, 23]])
print(np.sort(A))

[[20 22 25]
 [20 21 24]
 [23 26 27]]


In [27]:
B = np.array([[5, 2, 8, 1, 3],[7, 3, 4, 9, 5]])
print("Sort using axis = -1 : \n", np.sort(B, axis = -1))
print("Sort using axis = 0 : \n", np.sort(B, axis = 0))
print("Sort using axis = None : \n", np.sort(B, axis = None))
print("Sort using merge sort : \n", np.sort(B, kind = 'mergesort'))

Sort using axis = -1 : 
 [[1 2 3 5 8]
 [3 4 5 7 9]]
Sort using axis = 0 : 
 [[5 2 4 1 3]
 [7 3 8 9 5]]
Sort using axis = None : 
 [1 2 3 3 4 5 5 7 8 9]
Sort using merge sort : 
 [[1 2 3 5 8]
 [3 4 5 7 9]]


#### where() function
It is used for selecting elements based on a condition

In [20]:
m = np.array([[1, 9, 2, 8],[4, 7, 5, 6]])
print(np.where(m == 8))

(array([0], dtype=int64), array([3], dtype=int64))


In [25]:
m = np.array([[[2, 4, 6],[4, 6,  8],[6, 8, 0]],[[1, 3, 5],[3, 5, 7],[5, 7, 9]]])
print(np.where(m == 5))

(array([1, 1, 1], dtype=int64), array([0, 1, 2], dtype=int64), array([2, 1, 0], dtype=int64))


##### write a python statemnet to find out the position of 16 and 4

In [45]:
C = np.array([[3, 4, 5, 6, 7],[13, 14, 15, 16, 17],[23, 24, 25, 26, 27]])
print("Position of element 16 :", np.where(C == 16)[0],np.where(C == 16)[1])
print("Position of element 4 :", np.where(C == 4)[0],np.where(C == 4)[1])

Position of element 16 : [1] [3]
Position of element 4 : [0] [1]


__Method &emsp;&emsp; | &emsp;&emsp; Function Description__<br>
sum() &emsp;&emsp;&emsp;&nbsp; | &emsp;&emsp; It returns the sum of the array elements <br>
prod() &emsp;&emsp;&emsp; | &emsp;&emsp; It returns the product(multiplication) of the array elements <br>
max() &emsp;&emsp;&emsp;&nbsp; | &emsp;&emsp; It returns the maximum value of the array elements <br>
min() &emsp;&emsp;&emsp;&nbsp; | &emsp;&emsp; It returns the minimum value of the array elements <br>
mean() &emsp;&emsp;&nbsp;&nbsp; | &emsp;&emsp; It returns the mean of the array elements <br>
std() &emsp;&emsp;&emsp;&nbsp;&nbsp; | &emsp;&emsp; It returns the standard deviation of the array elements <br>
argmax() &emsp;&nbsp;&nbsp; | &emsp;&emsp; It returns the index of the maximum value in the array.<br>
argmin() &emsp;&nbsp;&nbsp; | &emsp;&emsp; It returns the index of the maximum value in the array.<br>

In [4]:
B = np.array([[2, 3, 4, 5],[3, 4, 5, 3],[5, 6, 7, 2]])
print(B)

[[2 3 4 5]
 [3 4 5 3]
 [5 6 7 2]]


In [7]:
print("Sum of elements of array : ", B.sum())
print("Product(multiplication) of elements of array : ", B.prod())
print("Maximum element of array : ", B.max())
print("Minimum element of array : ", B.min())
print("Mean of array elements : ", B.mean())
print("Standard deviation of array elements : ", B.std())
print("Position of maximum element of array : ", B.argmax())
print("Position of minimum element of array : ", B.argmin())

Sum of elements of array :  49
Product(multiplication) of elements of array :  9072000
Maximum element of array :  7
Minimum element of array :  2
Mean of array elements :  4.083333333333333
Standard deviation of array elements :  1.4976833963009524
Position of maximum element of array :  10
Position of minimum element of array :  0


In [3]:
n7 = np.array([[[[55, 65, 75, 85, 95], [50, 60, 70, 80, 90], [56, 57, 58, 59, 60]],
                [[11, 21, 31, 41, 51], [33, 44, 55, 66, 77], [83, 89, 84, 85, 81]],
                [[32, 42, 52, 62, 72], [34, 43, 54, 65, 76], [10, 20, 30, 40, 50]]],

               [[[10, 29, 38, 47, 56], [76, 67, 85, 58, 94], [31, 32, 33, 34, 35]],
                [[15, 26, 37, 48, 59], [27, 38, 49, 50, 16], [54, 63, 72, 81, 90]],
                [[5, 15, 25, 35, 45], [10, 20, 30, 40, 50], [13, 23, 33, 43, 53]]]])

In [5]:
print(n7[1][1][1])
print(n7[0][1][2][::-1])
print(n7[1][0][1][:3])
print(n7[0][2])
print(n7[0][2][2][2])
print(n7[1][2][1][2])
print(n7[0][0][2][0])
print(n7[1][0][0][4])
print(n7[0][1][1][4])
print(n7[1][0][1][1])

[27 38 49 50 16]
[81 85 84 89 83]
[76 67 85]
[[32 42 52 62 72]
 [34 43 54 65 76]
 [10 20 30 40 50]]
30
30
56
56
77
67


In [7]:
n4 = np.array([[[[3,4,5,6],[5,4,7,4],[5,7,9,8]],
                [[34,23,35,33],[22,23,24,25],[45,34,54,56]],
                [[21,22,23,24],[26,28,21,29],[25,23,27,22]]],
               
               [[[53,54,55,56],[51,44,47,14],[15,17,19,18]],
                [[64,63,65,13],[62,66,61,35],[67,68,69,71]],
                [[70,72,73,74],[81,84,82,88],[78,77,75,79]]]])

In [19]:
print(n4[1]) 
print(n4[0][1][0])
print(n4[0][2][1][:3])
print(n4[1][2][1])
print(n4[0][2])
print(n4[1][2][2][3])
print(n4[1][1][1][2])
print(n4[0][1][2][3])
print(n4[1][0][0][3])
print(n4[1][0][1][1])
print(n4[1][0][2][3])

[[[53 54 55 56]
  [51 44 47 14]
  [15 17 19 18]]

 [[64 63 65 13]
  [62 66 61 35]
  [67 68 69 71]]

 [[70 72 73 74]
  [81 84 82 88]
  [78 77 75 79]]]
[34 23 35 33]
[26 28 21]
[81 84 82 88]
[[21 22 23 24]
 [26 28 21 29]
 [25 23 27 22]]
79
61
56
56
44
18
